name: Upload Python Package

on:
    release:
        types: [published]

env:
    python-version: 3.12

jobs:
    # Write a test if the image `ghcr.io/fairmat-nfdi/nomad-north-voila:${{ github.ref_name }}` exists,
    # on file src/nomad_north_voila/north_tools/voila/__init__.py
    test-image:
        name: Test if image tag is updated
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Check if image tag is updated
              run: |
                  IMAGE_TAG=$(grep -oP "ghcr\.io/fairmat-nfdi/nomad-north-voila:\K[^'\",]+" src/nomad_north_voila/north_tools/voila/__init__.py)
                  if [[ "$IMAGE_TAG" != "${GITHUB_REF_NAME}" ]]; then
                      echo "Image tag in __init__.py is not updated to ${GITHUB_REF_NAME}"
                      echo "Found image tag: $IMAGE_TAG"
                      exit 1

    build:
        name: Build Package
        runs-on: ubuntu-latest
        needs: test-image
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Install uv and set the python version to ${{ env.python-version }}
              uses: astral-sh/setup-uv@v5
              with:
                  python-version: ${{ env.python-version }}
            - name: Build package
              run: uv build
            - name: Upload dist artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist-artifacts
                  path: dist/

    deploy:
        name: Upload to PyPI
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/nomad-north-voila
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: recursive
            - name: Download dist artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist-artifacts
                  path: dist/
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
